apiVersion: v1
kind: ConfigMap
metadata:
  name: ms-grafana-datasource-prometheus
  namespace: monitoring
  labels:
    grafana_datasource: '1'
data:
  datasource.yaml: |-
    apiVersion: 1
    deleteDatasources:
    - name: ms-prometheus

    datasources:
    - name: ms-prometheus
      type: prometheus
      access: proxy
      #url: http://prometheus-server.monitoring.svc.cluster.local
      orgId: 1
      url:http://prometheus.9melon.ru